apiVersion: v1
kind: Secret
metadata:
    name: longhorn-r2-backup
    namespace: longhorn-system
stringData:
    #ENC[AES256_GCM,data:oi+Q28macUxKlfFD5MBkam25CJ4I6if4NrdBbEEU3vlCgqeVHaobb1pZ2OEOmnZAjyQrySRkSaWjfVz3CBV5vP2NnQ8mWQev6Xs5jg==,iv:2JjjhLESJaGVgpcqDTeTelsy4Apt2vDQt4nZ3RgKews=,tag:OGuH9EVYdw3ruEiAT4kQwg==,type:comment]
    #ENC[AES256_GCM,data:Ws3RYI7E8E/MfzTMghXKE4BFdsLG1kc3pXXAA9/8KzoXPhhfGhGtEblRBkbX0/QyO6z0B3pZvw+z3+431CTmOqOWhbCStgKB,iv:qkO285oh1OqP6y2RqiWLg1jHyEqpnfO95y0LUT7CQY8=,tag:B+EbSDy8qIhw+JR8G6h83g==,type:comment]
    #ENC[AES256_GCM,data:AxW4UzeWh1IhQEDs499IWDHPypcTs7wrRSZ3m3p6J3xhCF1LMkyYeE2fJ5Nm2jjnzraYDW/pUw2lg+jj7NSqfZzFyg==,iv:iWnKtiqUK+aRjm7K1wpxDoMTweifkeMqwDeKrr9cDXk=,tag:LfbkUENCRJzHL397pRFwVA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sVb9FtaqteF8SZyH5QHvh+GA+6tAq38QCGSfs8Qv0FI=,iv:HVw+ZWOE1y2fFEPYn7U6idU8g2hAHyzi+idZa5hFPFI=,tag:37I+rY63MJVNlWM2PMi0Tg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kOU49WdrI5ewCsX6ADmrpQX57EQR2l6mEwnJ3hY4/4XsvoeMbHdbJs1Tx4gZhtKE0gKgiNNs+pMcc7Ebzb7rQg==,iv:qgRD4oFIkTTuGyMs/+cQsL8t9ZWKI2yxNj3Dc2XaJtE=,tag:3P1XNzlExiG+J6nR2X8x3Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:4Lh84Wsrcmq3sFP13QuvaAN+MWWneVB9zRKwfMpnUsYiGCo82z0FWJTO96qYO7DVj/OQ60tTfwRmu4AmuSbVhz8=,iv:ROZaiR17mdFBxOkl7/LTEagkY3eFOUm0PDafW+AXw8A=,tag:4rv4RgT2IHn9IF5JUd98CA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MjBzVk1QNUNYMmkrc0hK
            N1REeFNEUmVVNURka2xxenB1LzgrcUgzU0ZjClVoSW5USUZoVEZ6eGVxVkZLMWtv
            YmdaOTNoU094OWhBNkpKeVljdEhFTnMKLS0tIFRMWjIvb2hIblhEMjRObWNWdlZC
            UzFYeHRzQmxDWTJWZnJzVUM1UVNhT2cKOOETcFgzaFvNpVPqjavQ4H/5Ii2RVMHy
            rYCwf9u/9IGybiktKJ/IF9qGS6MmOTmt9g/o3nQIsAuI7cuzOmxouA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ar7n9wdlrjwmsjvdd3jpyda380crthvp804pvghvszj29lnxy6syyx6lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T23:57:50Z"
    mac: ENC[AES256_GCM,data:530w0ogFEt7NhMSBR+QhYpbxsbAEqjVTlfoRFSNc410YISueCiZbwaSfOt03sxX1JFa0VSG9lzySWMca/lApn6nITu2d09gUu8g15rKTrhsSgIJqhwX6EB3faBJ3LrgdtB4WTHB0Ro7qeD/JLNIma62C7XcWNyyL0eTVj/3lNJA=,iv:00OK/EoonTC9p/kIX+IMG1j4YmXV6fxlP3oZb4py648=,tag:XMuM33pANTE7XrJmkurODw==,type:str]
    version: 3.13.1
