apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
