kind: Deployment
apiVersion: apps/v1
metadata:
  name: me-site
  namespace: default
  labels:
    app: me-site
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: me-site
  template:
    metadata:
      labels:
        app: me-site
    spec:
      containers:
        - name: me-site
          image: ghcr.io/lexfrei/me-site:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: me-site
  labels:
    app: me-site
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: me-site
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: default
  name: me-site
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`me.k8s.home.lex.la`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: me-site
          port: 8080
