---
apiVersion: v1
kind: Secret
metadata:
  name: fix-multipath-secret
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    echo '
    blacklist {
        devnode "^sd[a-z0-9]+"
    }
    ' >> /etc/multipath.conf
    systemctl restart multipathd.service
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: fix-multipath-all
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: false
  nodeSelector:
    matchExpressions:
      - key: RandomKey
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  secrets:
    - name: fix-multipath-secret
      path: /host/run/system-upgrade/secrets
  version: focal
  upgrade:
    image: ubuntu:focal
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/upgrade.sh"]
