apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: me-site
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: me-site
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://lexfrei.github.io/charts"
    targetRevision: "0.3.0"
    chart: me-site
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: tunnel

            external-dns.alpha.kubernetes.io/hostname: "aleksei.sviridk.in"
            external-dns.alpha.kubernetes.io/target: "fe8f0ad1-3ace-4f89-b904-ed17fe7e0eeb.cfargotunnel.com"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          hosts:
            - host: aleksei.sviridk.in
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: me-site
                      port:
                        number: 8080
  project: workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
