apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: workloads
  destination:
    namespace: transmission-system
    server: "https://kubernetes.default.svc"
  sources:
    - path: manifests/transmission
      repoURL: https://github.com/lexfrei/k8s.git
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
