apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: traefik
  namespace: traefik-system
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
