apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://victoriametrics.github.io/helm-charts/"
    targetRevision: "0.21.1"
    chart: victoria-metrics-k8s-stack
    helm:
      valuesObject:
        grafana:
          enabled: false
        prometheus-node-exporter:
          enabled: true
        vmsingle:
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              cert-manager.io/cluster-issuer: cloudflare-issuer
            hosts:
              - "vm.k8s.home.lex.la"
            tls:
              - secretName: vm-tls
                hosts:
                  - vm.k8s.home.lex.la
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
