apiVersion: v1
data:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:HxfhpFcd3TBO6nYImNB449itsLdznfWEBMJWRA==,iv:WhUqH06cimCD4HXTuBt6NDU9ghPAsvsFQmLPhHhii98=,tag:F+fALkzmSc6do5CaNw/3sg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:T67qhvYVCaU=,iv:Yd05AGzlMOZmvVTEheadfknUfJN770kolabH9bnFA3Q=,tag:DqtXvDEMBUV5hKRd41V4fw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:wWATMBL/eWKs3cQoKKvwgyBs0N9vsFSTDb6vHwVenn4q2xvywrZGjsDWVrbSuT/H8YEA6pHmFylijSCMJU1Mp6kEm3pCpRUtOq/Z2isNTOgVPh9VvVSnhQ==,iv:Yx9ocEElKrFpEpYhkI9ZLpPlXEWn88t0D5PGTSCnSjU=,tag:riVvFoTZ7IhKE6P5r8+J1Q==,type:str]
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aHlzYi84dkdhenRVU3Jo
            QjdicEVIVkZwZjZDL2xzWWU3MmxGRHREaUIwCktoZk05U2J6RXBlZDJkVy9NRXI4
            SGorSjRiT2F6NXRrdWY4NUYzd0tPYVkKLS0tIDExMEs1S2NCOUI4TURhQTN2aWZ6
            ekNOMHR6US9QWGRVSmkzZnp4bTdzeHcKlLJM6oEKMsyy2QkXtlL4cJPEg6KbPxA6
            8hL+e/YyOGSvJsmLLf0w90dS0UQ1ArN74Y0rko8khXQv8Dia5IGj3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ar7n9wdlrjwmsjvdd3jpyda380crthvp804pvghvszj29lnxy6syyx6lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T09:12:51Z"
    mac: ENC[AES256_GCM,data:W/84oimpNFhhKNDF+UHNqos0//kBhKiTNwA4YWgbhOltXflPEr81bIGJXnTuQnwGXYshFRhsZUDnT8kxgUUSc9PXboHimYnbXJJ/v77G7F73dJkhbFZ4A/ni9aA0NLtcBxHAmf7g0c3srhP2s5NcPnOgfvQ1exkvHKUVOzKGG44=,iv:zgIMYmm/bDqOGjPh1QT2bOdLdeQ4N8IN6WdXMZMzfdU=,tag:mKJV2PQkLoNc2HCAueFtQg==,type:str]
    version: 3.13.1
