kind: Deployment
apiVersion: apps/v1
metadata:
  name: vk2tg
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vk2tg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vk2tg
    spec:
      containers:
        - name: vk2tg
          image: ghcr.io/lexfrei/vk2tg/vk2tg:sha-97eea0c
          envFrom:
            - secretRef:
                name: vk2tg
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
