apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-certificate
spec:
  secretName: traefik-tls-secret
  dnsNames:
    - traefik.k8s.home.lex.la
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
