apiVersion: tor.k8s.torproject.org/v1alpha2
kind: OnionService
metadata:
  name: traefik-onion-service
  namespace: traefik-system
spec:
  version: 3
  rules:
    - port:
        number: 80
      backend:
        service:
          name: traefik
          port:
            number: 80