---
apiVersion: v1
kind: Secret
metadata:
  name: system-upgrade-secret
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    dpkg --configure -a
    apt-get -q update
    apt-get -qy dist-upgrade --auto-remove --purge
    if [ -f /var/run/reboot-required ]; then
      echo 'reboot' | at midnight + 5hours
    fi
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: system-upgrade-server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: Exists }
  serviceAccountName: system-upgrade
  secrets:
    - name: system-upgrade-secret
      path: /host/run/system-upgrade/secrets
  version: focal
  upgrade:
    image: ubuntu:focal
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/upgrade.sh"]
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: system-upgrade-agent-plan
  namespace: system-upgrade
spec:
  concurrency: 3
  nodeSelector:
    matchExpressions:
      - { key: node-role.kubernetes.io/control-plane, operator: DoesNotExist }
  serviceAccountName: system-upgrade
  secrets:
    - name: system-upgrade-secret
      path: /host/run/system-upgrade/secrets
  version: focal
  upgrade:
    image: ubuntu:focal
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/upgrade.sh"]
