apiVersion: v1
kind: Service
metadata:
  name: transmission
  annotations:
    metallb.io/address-pool: transmission-pool
spec:
  type: LoadBalancer
  selector:
    app: transmission
  ports:
    - name: http
      protocol: TCP
      port: 9091
      targetPort: http
    - name: torrent-tcp
      protocol: TCP
      port: 51413
      targetPort: torrent-tcp
    - name: torrent-udp
      protocol: UDP
      port: 51413
      targetPort: torrent-udp
