apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: "7.3.7"
    chart: grafana
    helm:
      valuesObject:
        persistence:
          enabled: true
          type: pvc
          size: 10Gi
          storageClassName: longhorn
        adminPassword: admin
        ingress:
          enabled: true
          hosts:
            - grafana.k8s.home.lex.la
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.k8s.home.lex.la
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
