apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-k8s-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://victoriametrics.github.io/helm-charts/"
    targetRevision: "0.20.0"
    chart: victoria-metrics-k8s-stack
    helm:
      valuesObject:
        ingress:
          enabled: true
          hosts:
            - host: vm.k8s.home.lex.la
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          tls:
            - secretName: vm-tls
              hosts:
                - vm.k8s.home.lex.la
        grafana:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
