kind: Deployment
apiVersion: apps/v1
metadata:
  name: vk2tg
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vk2tg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vk2tg
    spec:
      containers:
        - name: vk2tg
          image: ghcr.io/lexfrei/vk2tg:sha-0f0d8ac
          envFrom:
            - secretRef:
                name: vk2tg
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
        - name: redis
          image: redis:6.2.6-alpine
          command:
            - redis-server
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
              memory: 100Mi
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-main
  resources:
    requests:
      storage: 500Mi
