apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:uEB3hmFCaAkCYawELYgxChMslG+rSBUFsK443vs3zp+rbQ297y/yZo3pMpLjZ2R36NfwqWHe2j6AlYBqk7KQHExgxBoJAT1zss06f93/4LsE8IgmqOE/0bnBzqpXUTPp971c7MBRnYyC2onkhC/Ms30do77sC9VW7ubGe96ff2bKCGDGjlQ586Xt3E+nAcF+80EV5PFua3RwK3yFODDTL5JjhSfMDlEQFHnQ3sV9qzIwKPnH7jMZ2Ys1jQOrt0+BmJenEx4APUU66oqd896kSyPnsosrB9rpWu1m0SBzleNUg0Ou/Qda1CrAyA2nEPV7,iv:OGsnBJ+axArSVDvCZ670WCamuEf+584kkJ3XXzI520U=,tag:n+kbmWe1f6LPTinvkm5gsg==,type:str]
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOE93OE1JRFdaNlVIanVZ
            WXhFK0JZbjZmVUllS3NtZkdxbEZwQjhuNUdJCjhwcU83TGlzZFdPWnhjWHViQnU2
            aXB5bHlqejUzQVBmZ08vOER5dzQ0VXMKLS0tIDVjVkU0bGhjaHliQk04L3hFN2NB
            R3V4anZNM2xUeW1RVVJOZWNPckVTLzgKaDCgwxnLmoK9nLr2Hc7HwvGUu+eDFsz8
            D2u84C1zUqL/4KcjmXL8JJ9TaA6lKLXinXOmaQ3xFVXAECXhlSnuBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ar7n9wdlrjwmsjvdd3jpyda380crthvp804pvghvszj29lnxy6syyx6lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T09:10:12Z"
    mac: ENC[AES256_GCM,data:4504z/vz09OVizGNF6UwSN87TpzF+BMHTGOv3jybPCxrtZ5wuGtCe3IOZJUM9frxeEeiHjXkBMLr+6U9XxPZ5tqoxTZ+y2nboaOfD9XFdQq7Uek1KVQQG03OIaQJsm4qAMqkH02CwT8CiME1AakOx+1j9VTvu7h5iS/bI9s7rhw=,iv:ys7Q7xazxwaJlVKWVdkCZliJtxukJbTC0Hq2XmXoCcA=,tag:3McwBkDYEuEZpaZU1U9MUA==,type:str]
    version: 3.13.1
