repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  # https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-single
  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    version: 6.4.4
    installed: true
    values:
      - ingress:
          enabled: true
          hosts: ["grafana.k8s.home.lex.la"]
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        persistence:
          enabled: true
          size: 1Gi
