repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  # https://artifacthub.io/packages/helm/k8s-at-home/heimdall
  - name: heimdall
    namespace: heimdall
    installed: false
    chart: k8s-at-home/heimdall
    values:
      - ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            hosts:
              - host: start.k8s.home.lex.la
                paths:
                  - path: /
        persistence:
          config:
            enabled: true
