repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
  # https://artifacthub.io/packages/helm/k8s-at-home/home-assistant
  - name: home-assistant
    namespace: home-assistant
    installed: true
    chart: k8s-at-home/home-assistant
    version: 5.5.1
    values:
      - ingress:
          enabled: true
          hosts:
            paths:
              - ha.k8s.home.lex.la
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
