repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # https://hub.helm.sh/charts/bitnami/metallb
  - name: metallb
    namespace: metallb-system
    installed: true
    chart: bitnami/metallb
    values:
      - controller:
          image:
            repository: metallb/controller
            tag: v0.9.5
        speaker:
          secretValue: wXuJ5Ronmdq9uG9YlsuF0X2BURyBLz9a34AqsymDwDMleiLTbKApW0mpgI3GulPqGrihWCBjEo5CdNTUkTy9YnvVPu6t8xDFkJrloZ8HVr6GYpjGTL8o715le0dmazHZbyZDkqYFzOaeXZs3q8BZFmysAe1B9zVsEszt1gFgh0uGicibkXgjCyl4E0J3WKpbeIhtDgu1BxR99CHTtI8480teb943Pok2cEJ4pnXb7WWhVMzJCqRJmWv9LwhUTUXH
          image:
            repository: metallb/speaker
            tag: v0.9.5
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.6.0/24
          - name: traefik
            protocol: layer2
            addresses:
            - 192.168.5.200/32

  # https://artifacthub.io/packages/helm/traefik/traefik
  #
  # Check this page before upgrade
  # https://doc.traefik.io/traefik/migration/v2/
  #
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    installed: true
    values:
      - service:
          annotations:
            metallb.universe.tf/address-pool: traefik
        additionalArguments:
          # Disable internal ssl check
          - "--serversTransport.insecureSkipVerify=true"
          # SSL for prod
          - "--certificatesresolvers.prodssl.acme.dnschallenge.provider=cloudflare"
          - "--certificatesresolvers.prodssl.acme.storage=/data/acme.json"
          - "--certificatesresolvers.prodssl.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
          - "--entrypoints.websecure.http.tls=true"
          - "--entrypoints.websecure.http.tls.certresolver=prodssl"
        globalArguments:
          - "--global.checknewversion"
        persistence:
          enabled: true
        deployment:
          initContainers:
            # The "volume-permissions" init container is required if you run into permission issues.
            # Related issue: https://github.com/traefik/traefik/issues/6972
            - name: volume-permissions
              image: busybox:1.31.1
              command: ["sh", "-c", "chmod -Rv 600 /data/*"]
              volumeMounts:
                - name: data
                  mountPath: /data
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cf-token
                key: token
        ports:
          web:
            redirectTo: websecure
