repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  # Check the link in case of major update
  - name: kube-prometheus-stack
    namespace: monitoring
    installed: true
    chart: prometheus-community/kube-prometheus-stack
    version: 14.6.2
    values:
      - grafana:
          enabled: false
