repositories:
  - name: longhorn
    url: https://charts.longhorn.io

# https://artifacthub.io/packages/helm/longhorn/longhorn
releases:
  - name: longhorn
    namespace: longhorn-system
    installed: true
    chart: longhorn/longhorn
    version: 1.1.0
    values:
      - defaultSettings:
          defaultDataPath: "/mnt/storage"
        ingress:
          enabled: true
          host: longhorn.k8s.home.lex.la
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
