# repositories:
#   - name: longhorn
#     url: https://charts.longhorn.io
# https://artifacthub.io/packages/helm/longhorn/longhorn
# https://longhorn.io/docs/1.0.2/deploy/install/install-with-helm
# Replace local chart with official one asap
# https://github.com/longhorn/longhorn/milestone/17

releases:
  - name: longhorn
    namespace: longhorn-system
    installed: true
    chart: ../charts/longhorn
    values:
      - defaultSettings:
          defaultDataPath: "/mnt/storage"
        ingress:
          enabled: true
          host: longhorn.k8s.home.lex.la
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
