# https://github.com/metallb/metallb/milestone/10
# Replace repo asap

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # https://hub.helm.sh/charts/bitnami/metallb
  - name: metallb
    namespace: metallb-system
    installed: true
    chart: bitnami/metallb
    version: 1.1.0
    values:
      - controller:
          image:
            repository: metallb/controller
            tag: v0.9.5
        speaker:
          image:
            repository: metallb/speaker
            tag: v0.9.5
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 192.168.6.0/24
          - name: traefik
            protocol: layer2
            addresses:
            - 192.168.5.200/32
