repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: victoria-metrics
    url: https://victoriametrics.github.io/helm-charts/

releases:    
  # https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack
  - name: victoria-metrics-k8s-stack
    namespace: monitoring
    chart: victoria-metrics/victoria-metrics-k8s-stack
    installed: true
    values:
      - grafana:
          enabled: false
        vmsingle:
          spec:
            retentionPeriod: "12"
            replicaCount: 1
            removePvcAfterDelete: true
            storage:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 4Gi
        vmagent:
          enabled: true
          spec:
            scrapeInterval: 25s
            extraArgs:
              promscrape.streamParse: "true"

  - name: grafana
    namespace: monitoring
    chart: grafana/grafana
    installed: true
    values:
      - ingress:
          enabled: true
          hosts: 
            - grafana.k8s.home.lex.la
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        adminPassword: admin
        ## Dashboards
        dashboards:
          default:
            victoriametrics:
              url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/master/dashboards/victoriametrics.json
            vmagent:
              url: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/master/dashboards/vmagent.json
            nodeexporter:
              gnetId: 1860
              revision: 22
              datasource: VictoriaMetrics
            prometheus-stats:
              gnetId: 11074
              revision: 9
              datasource: VictoriaMetrics
            longhorn-stats:
              gnetId: 13032
              revision: 6
              datasource: VictoriaMetrics
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        ##
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: VictoriaMetrics
                type: prometheus
                url: "http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc:8429"
                access: proxy
                isDefault: true
        sidecar:
          datasources:
            enabled: true
          dashboards:
            enabled: true
        persistence:
          enabled: true
          size: 1Gi