repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  # https://artifacthub.io/packages/helm/traefik/traefik
  #
  # Check this page before upgrade
  # https://doc.traefik.io/traefik/migration/v2/
  #
  - name: traefik
    namespace: traefik-system
    chart: traefik/traefik
    version: 9.11.0
    installed: true
    values:
      - ingressRoute:
          dashboard:
            enabled: true
        service:
          annotations:
            metallb.universe.tf/address-pool: traefik
        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--certificatesresolvers.stagessl.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
          - "--certificatesresolvers.stagessl.acme.dnschallenge.provider=cloudflare"
          - "--certificatesresolvers.stagessl.acme.storage=/data/stage-acme.json"
          # - "--log.level=DEBUG"
        globalArguments:
          - "--global.checknewversion"
        env:
          - name: CLOUDFLARE_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: tokens
                key: cf-token
        persistence:
          enabled: true
