repositories:
  - name: victoria-metrics
    url: https://victoriametrics.github.io/helm-charts/

releases:
  # https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-single
  - name: victoria-metrics-single
    namespace: monitoring
    chart: victoria-metrics/victoria-metrics-single
    installed: false
