---
apiVersion: v1
kind: Secret
metadata:
  name: system-upgrade-secret
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    apt update && apt upgrade -y
    apt autoremove -y
    if [ -f /var/run/reboot-required ]; then
      reboot
    fi
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: system-upgrade-server
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  secrets:
    - name: system-upgrade-secret
      path: /host/run/system-upgrade/secrets
  version: focal
  upgrade:
    image: ubuntu:noble
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/upgrade.sh"]
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: system-upgrade-agent
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  secrets:
    - name: system-upgrade-secret
      path: /host/run/system-upgrade/secrets
  version: focal
  upgrade:
    image: ubuntu:noble
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/upgrade.sh"]