apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cf-issuer
  namespace: cert-manager
spec:
  acme:
    email: f@lex.la
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cf-issuer-secret
    solvers:
    - dns01:
        cloudflare:
          email: f@lex.la
          apiTokenSecretRef:
            name: cf-token
            key: token