apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
stringData:
    #ENC[AES256_GCM,data:OViDQe+pYfQS3tzkJZPVBFJSEI0p9LdV8oaCEFPONKTbZH8V9makPeedxo3vqciFi8X6LA1y5Sc38Lbdm/KgdCtbxfJvuZvYlOlb6pxn,iv:oOhmx31rFPnzbZHEdxejAdi9OiVJCQ5mKivlgr05qrk=,tag:pidLzTPjE/ybsda1sniEXQ==,type:comment]
    #ENC[AES256_GCM,data:SQd17BMtXOgTgIsjrnacbJirdZzPQjgxVwHQ//dM/zwUpgYBe00B8YBJCp46Yaul4+STETeuMhJKjng=,iv:JI3xwiTrVb8zCMxgO32Qw3e5187esf5qhSfCshsQ4bc=,tag:ney0Uy7o/2TKkyK1VeMHuQ==,type:comment]
    DB_PASSWORD: ENC[AES256_GCM,data:Iet2ocKeJSYq/GhV,iv:Udadgeinzz3J8OibU1EjMBJjdiZF8NZJMhYOyWOAwMI=,tag:QNOxwLqqQA8tWV6LNvsPnA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7O7vaDbZvkmyBSvB,iv:42F6sdE5nuVmnQZW+A8jY/jeuLlQd/b5cRjTp04CseY=,tag:UHMzcudZPHUx3qinz/HUfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bDJ1QUNQWXFrL1NiNXQ3
            SnU5SUdaaTJNUmorODBtWktaTWcyMlEvZEhNClZoVENhOVRTZGE0c2hMZGxGOUwv
            ZUFMREJVd1BXNG1yZGl4RW5rL3ZrdXcKLS0tIGFQRnZIOFFVRGJUMUZuMEUrNjJT
            UXk0SUh5QWdEeldyTlVYbnNybVlTTFEK53xDVgRlj4Oag1re4+W9OGPmV9YBX02k
            oGRTu1LEsU6zaTjoPm9s/wyZWNrpUZpF3F7bNZAaq5oQmHS6RuaLdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ar7n9wdlrjwmsjvdd3jpyda380crthvp804pvghvszj29lnxy6syyx6lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T19:27:09Z"
    mac: ENC[AES256_GCM,data:Tgb2MohddaxkGRkZgGm7zSKwW1q1lAbrfduwv0P5ExXaHSswKND2oJSuHv9al9rE2v2dj6BwCPObEyl3TKuuq5AUfCVh2LSXVBtuDq0Si4Mf5HypQfrQioPDFJE1/kVBWEaMJB0G+uoqtzHUrkWc9T8O2LYkWjNNv3+AuzApSeo=,iv:DqEH3ewHkaQ37uMLa5lwpSWzBLobiPmQFUiLnnGZOvQ=,tag:jCyHlIuYrxSCs0Boj6kDDw==,type:str]
    version: 3.13.1
