apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: "6.7.13"
    chart: argo-cd
    helm:
      values: |
        global:
          domain: argocd.lex.la
          logging:
            level: debug
        configs:
          params:
            server:
              insecure: true
          cm:
            resource.compareoptions: |
              # disables status field diffing in specified resource types
              ignoreAggregatedRoles: true
        server:
          ingress:
            enabled: true
            hosts:
              - host: argocd.lex.la
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: argocd-server
                        port:
                          number: 80
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure,tunnel
              cert-manager.io/cluster-issuer: cloudflare-issuer
            tls:
              - secretName: argocd-lex-la-tls
                hosts:
                  - argocd.lex.la
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
