apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: smarthome
  destination:
    namespace: plex-system
    server: "https://kubernetes.default.svc"
  sources:
    - chart: plex-media-server
      repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      targetRevision: 0.8.0
      helm:
        valuesObject:
          ingress:
            enabled: true
            ingressClassName: "traefik"
            url: "plex.lex.la"
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: tunnel

              external-dns.alpha.kubernetes.io/hostname: "plex.lex.la"
              external-dns.alpha.kubernetes.io/target: "fe8f0ad1-3ace-4f89-b904-ed17fe7e0eeb.cfargotunnel.com"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

          pms:
            storageClassName: nfs-csi
            configStorage: 2Gi
            resources:
              limits:
                cpu: "1"
                memory: "2Gi"
              requests:
                cpu: "500m"
                memory: "1Gi"

          extraEnv:
            TZ: "Europe/Moscow"
            PLEX_UID: "1000"
            PLEX_GID: "1000"

          extraVolumeMounts:
            - name: downloads
              mountPath: /downloads
              readOnly: true

          extraVolumes:
            - name: downloads
              nfs:
                server: nas.home.lex.la
                path: /nfs/Transmission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
