apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:8JZCIhTy0huwvRux+VVloPfQSFiFkFVS5/UTK+yzE2nTwis1PuX7gR+gYeGHab0TE3tRobqv1ICmAm/NWTWiQG7u2KdW0+Hw,iv:VwnaOSUrbO1mxHL2AvCqMAhmOf0tYdhN7XkM7AXwz+8=,tag:93ZksFlrNVcbtC7hWI+oaQ==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NTlLYmlIZjJXVUtPQWxr
            ZXV2KzBteEtoeEZzUFExTDZBWmZDZEVPS21ZCnNCR2pqeDE3UFg0cmRLeUtZM09S
            bzI4MzJ1MjlXU0ErV3RMUmlzemhqaDgKLS0tIHhiR3A4bDJUTStyZXZLTWhxTGk1
            bGpOQkJnK3ZNSnI5dGsrL3duaEJIajAK5llHv/kWbHqGsbbM7MRwZzvo+GqMwU8Z
            Bw+2+W8TSw8zn0fu/ebiHA7atXD1OpauWIDlvKXRL9/JrceFM3/muw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ar7n9wdlrjwmsjvdd3jpyda380crthvp804pvghvszj29lnxy6syyx6lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T21:30:40Z"
    mac: ENC[AES256_GCM,data:6S7MuFFTm3jHHbKFrhPOF1Ab9+IKoqH5LJmqaOa5JCDPxl7akwvpABRY3oeDqVJkbF9ZdHu2TKQNmsL2nFsk7Xbm1jJrVzTDXLtTjU5eacL7ot42vuZttlVA/Hq/48JtyP4LxE+4Oh0in8Vlf6QsWpxWnAaw1QtEpx+lg8EBPeQ=,iv:sGPTbObLYcNSe5IsGzty8rVhduSU+j7D6+lqXDEZnM8=,tag:ULuYo+68zwHZt73VJoIGMQ==,type:str]
    version: 3.13.1
