apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
data:
  configuration.yaml: |-
    # Loads default set of integrations. Do not remove.
    default_config:

    # Enable the frontend and load themes from 'themes' directory
    frontend:
      themes: !include_dir_merge_named themes

    # Include YAML files
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 0.0.0.0/0
