apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-service
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: tunnel
spec:
  ingressClassName: traefik
  rules:
    - host: ha.lex.la
      http:
        paths:
          - backend:
              service:
                name: ha-service
                port:
                  name: http
            path: /
            pathType: Prefix
